### PR TITLE
Detect references in computed property names.

### LINKED ISSUE #73: References are not detected in computed property names.
Reproduction: https://observablehq.com/d/ac1f28041d650918

```js
foo = ({[field]: value}) => value
```
```js
field = "bar"
```
```js
foo({bar: 42})
```

Expected behavior: the last cell evaluates to 42.
Observed behavior: the last throws ReferenceError: field is not defined

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #73.

### CODE REVIEW

File: src/walk.js [hunk 1]
```diff
@@ -6,8 +6,8 @@ export default make({
     c(node.argument, st, "Expression");
   },
   ObjectPattern(node, st, c) {
-    const list = node.properties;
-    for (const prop of list) {
+    for (const prop of node.properties) {
+      if (prop.computed) c(prop.key, st, "Pattern");
       c(prop.value || prop.argument, st, "Pattern");
     }
```
Comment (tmcw) [inline src/walk.js]: I think we can / should remove ObjectPattern here – acorn-walk has its own implementation that we're overriding and doesn't have the bug this is fixing.

Comment (mbostock) [reply src/walk.js]: Good call! I’ve removed the now unnecessary overrides of ObjectPattern and SpreadPattern (the latter of which is now called SpreadElement).
